services:
    db:
        image: 'postgres'
        container_name: db
        volumes:
            - 'db_volume:/var/lib/postgresql/data'
        env_file:
            - config/db/db_env
        networks:
            - db_network
        expose:
            - '5432:5432'

    django:
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE
        volumes:
            - '.:/usr/src/app'
            - 'static:/usr/src/app/static'
        networks:
            - db_network
            - nginx_network
        depends_on:
            - db
        links:
            - 'db:db'
            
    nginx:
        image: 'nginx'
        ports:
            - '8000:80'
        volumes:
            - './config/nginx/conf.d:/etc/nginx/conf.d'
            - 'static:/usr/src/app/static'
        networks:
            - nginx_network
        depends_on:
            - django
            
networks:
    db_network:
        driver: bridge
    nginx_network:
        driver: bridge
        
volumes:
    db_volume: null
    static: null

